# Generated by Django 3.1.4 on 2021-01-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=120)),
                ('syls', models.CharField(max_length=120, verbose_name='5-7-5')),
            ],
        ),
    ]
